name: DBT CI/CD with Asset Bundles

on:
  push:
    branches:
      - main
jobs:
  dbt-dev:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_CLI }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID_CLI }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_TOKEN_CLI }}
      DATABRICKS_AUTH_TYPE: databricks-client-creds
      DBT_PROFILES_DIR: ./db_asset_bundle_sample/profiles/ 
      DBT_PROJECT_DIR: ./db_asset_bundle_sample

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install databricks cli
        run: |
          pip install --upgrade pip
          pip install databricks-cli

      - name: Verify Databricks CLI Authentication
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_CLI }}
          export DATABRICKS_CLIENT_ID=${{ secrets.DATABRICKS_CLIENT_ID_CLI }}
          export DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_TOKEN_CLI }}
          export DATABRICKS_AUTH_TYPE=databricks-client-creds

          echo "Testing Databricks CLI authentication..."
          databricks current-user get


      - name: Build dbt Asset Bundle
        run: |
          zip -r dbt_bundle_dev.zip ./db_asset_bundle_sample

      - name: Deploy dbt Asset Bundle to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_CLI }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_CLI }}
        run: |
          databricks workspace import --overwrite --language PYTHON dbt_bundle_dev.zip /Repos/my_org/dbt_bundle_dev